title: Homepage of Jintao Huang
page-top-title: Jintao Huang
#top-section-bg-text: Be what you wanna be
home-subtitle: Jintao Huang | 黄锦涛
copyright-text: '2022-2027. 黄锦涛 Jintao Huang. All Rights Reserved.'
